EES-1312 Analyst should be Data Analyst & flag all as HappyPath.
dfe-analytical-services/explore-education-statistics pull request #1949
Opened 2020-08-24 14:27 UTC by shakes90

2020-08-24 14:47 UTC, ntsim commented
Although I'm sure this suite runs for you locally, I get the complete opposite and it fails 100% of the time on the `Validate Analyst1 cannot see Upload data files` step (the list data files API throws a 500) with the following exception:

```
System.InvalidOperationException: Enumerator failed to MoveNextAsync.
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at GovUk.Education.ExploreEducationStatistics.Admin.Services.ReleaseFilesService.GetFilenameAssociatedToType(Guid releaseId, String filename, ReleaseFileTypes type, ReleaseFileTypes associatedType) in /home/nick/Development/personal/explore-education-statistics/src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFilesService.cs:line 635
   at GovUk.Education.ExploreEducationStatistics.Admin.Services.ReleaseFilesService.<>c__DisplayClass18_0.<<ListDataFilesAsync>b__0>d.MoveNext() in /home/nick/Development/personal/explore-education-statistics/src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFilesService.cs:line 315
--- End of stack trace from previous location where exception was thrown ---
   at GovUk.Education.ExploreEducationStatistics.Common.Model.EitherTaskExtensions.OnSuccess[Tl,Tr,T](Task`1 task, Func`2 func) in /home/nick/Development/personal/explore-education-statistics/src/GovUk.Education.ExploreEducationStatistics.Common/Model/Either.cs:line 157
   at GovUk.Education.ExploreEducationStatistics.Admin.Services.ReleaseFilesService.ListDataFilesAsync(Guid releaseId) in /home/nick/Development/personal/explore-education-statistics/src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFilesService.cs:line 287
   at GovUk.Education.ExploreEducationStatistics.Common.Extensions.EitherTaskExtensions.HandleFailuresOrOk[T](Task`1 validationErrorsRaisingAction) in /home/nick/Development/personal/explore-education-statistics/src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/EitherTaskExtensions.cs:line 30
   at GovUk.Education.ExploreEducationStatistics.Admin.Controllers.Api.ReleasesController.GetDataFilesAsync(Guid releaseId) in /home/nick/Development/personal/explore-education-statistics/src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ReleaseController.cs:line 112
   at lambda_method(Closure , Object )
```

2020-08-24 14:47 UTC, ntsim requested changes
Although I'm sure this suite runs for you locally, I get the complete opposite and it fails 100% of the time on the `Validate Analyst1 cannot see Upload data files` step (the list data files API throws a 500) with the following exception:

```
System.InvalidOperationException: Enumerator failed to MoveNextAsync.
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at GovUk.Education.ExploreEducationStatistics.Admin.Services.ReleaseFilesService.GetFilenameAssociatedToType(Guid releaseId, String filename, ReleaseFileTypes type, ReleaseFileTypes associatedType) in /home/nick/Development/personal/explore-education-statistics/src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFilesService.cs:line 635
   at GovUk.Education.ExploreEducationStatistics.Admin.Services.ReleaseFilesService.<>c__DisplayClass18_0.<<ListDataFilesAsync>b__0>d.MoveNext() in /home/nick/Development/personal/explore-education-statistics/src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFilesService.cs:line 315
--- End of stack trace from previous location where exception was thrown ---
   at GovUk.Education.ExploreEducationStatistics.Common.Model.EitherTaskExtensions.OnSuccess[Tl,Tr,T](Task`1 task, Func`2 func) in /home/nick/Development/personal/explore-education-statistics/src/GovUk.Education.ExploreEducationStatistics.Common/Model/Either.cs:line 157
   at GovUk.Education.ExploreEducationStatistics.Admin.Services.ReleaseFilesService.ListDataFilesAsync(Guid releaseId) in /home/nick/Development/personal/explore-education-statistics/src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFilesService.cs:line 287
   at GovUk.Education.ExploreEducationStatistics.Common.Extensions.EitherTaskExtensions.HandleFailuresOrOk[T](Task`1 validationErrorsRaisingAction) in /home/nick/Development/personal/explore-education-statistics/src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/EitherTaskExtensions.cs:line 30
   at GovUk.Education.ExploreEducationStatistics.Admin.Controllers.Api.ReleasesController.GetDataFilesAsync(Guid releaseId) in /home/nick/Development/personal/explore-education-statistics/src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ReleaseController.cs:line 112
   at lambda_method(Closure , Object )
```

2020-08-25 12:30 UTC, markhiveit commented
> Although I'm sure this suite runs for you locally, I get the complete opposite and it fails 100% of the time on the `Validate Analyst1 cannot see Upload data files` step (the list data files API throws a 500) with the following exception:
> 
> ```
> System.InvalidOperationException: Enumerator failed to MoveNextAsync.
>    at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
>    at GovUk.Education.ExploreEducationStatistics.Admin.Services.ReleaseFilesService.GetFilenameAssociatedToType(Guid releaseId, String filename, ReleaseFileTypes type, ReleaseFileTypes associatedType) in /home/nick/Development/personal/explore-education-statistics/src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFilesService.cs:line 635
>    at GovUk.Education.ExploreEducationStatistics.Admin.Services.ReleaseFilesService.<>c__DisplayClass18_0.<<ListDataFilesAsync>b__0>d.MoveNext() in /home/nick/Development/personal/explore-education-statistics/src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFilesService.cs:line 315
> --- End of stack trace from previous location where exception was thrown ---
>    at GovUk.Education.ExploreEducationStatistics.Common.Model.EitherTaskExtensions.OnSuccess[Tl,Tr,T](Task`1 task, Func`2 func) in /home/nick/Development/personal/explore-education-statistics/src/GovUk.Education.ExploreEducationStatistics.Common/Model/Either.cs:line 157
>    at GovUk.Education.ExploreEducationStatistics.Admin.Services.ReleaseFilesService.ListDataFilesAsync(Guid releaseId) in /home/nick/Development/personal/explore-education-statistics/src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFilesService.cs:line 287
>    at GovUk.Education.ExploreEducationStatistics.Common.Extensions.EitherTaskExtensions.HandleFailuresOrOk[T](Task`1 validationErrorsRaisingAction) in /home/nick/Development/personal/explore-education-statistics/src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/EitherTaskExtensions.cs:line 30
>    at GovUk.Education.ExploreEducationStatistics.Admin.Controllers.Api.ReleasesController.GetDataFilesAsync(Guid releaseId) in /home/nick/Development/personal/explore-education-statistics/src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ReleaseController.cs:line 112
>    at lambda_method(Closure , Object )
> ```



> Although I'm sure this suite runs for you locally, I get the complete opposite and it fails 100% of the time on the `Validate Analyst1 cannot see Upload data files` step (the list data files API throws a 500) with the following exception:
> 
> ```
> System.InvalidOperationException: Enumerator failed to MoveNextAsync.
>    at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
>    at GovUk.Education.ExploreEducationStatistics.Admin.Services.ReleaseFilesService.GetFilenameAssociatedToType(Guid releaseId, String filename, ReleaseFileTypes type, ReleaseFileTypes associatedType) in /home/nick/Development/personal/explore-education-statistics/src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFilesService.cs:line 635
>    at GovUk.Education.ExploreEducationStatistics.Admin.Services.ReleaseFilesService.<>c__DisplayClass18_0.<<ListDataFilesAsync>b__0>d.MoveNext() in /home/nick/Development/personal/explore-education-statistics/src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFilesService.cs:line 315
> --- End of stack trace from previous location where exception was thrown ---
>    at GovUk.Education.ExploreEducationStatistics.Common.Model.EitherTaskExtensions.OnSuccess[Tl,Tr,T](Task`1 task, Func`2 func) in /home/nick/Development/personal/explore-education-statistics/src/GovUk.Education.ExploreEducationStatistics.Common/Model/Either.cs:line 157
>    at GovUk.Education.ExploreEducationStatistics.Admin.Services.ReleaseFilesService.ListDataFilesAsync(Guid releaseId) in /home/nick/Development/personal/explore-education-statistics/src/GovUk.Education.ExploreEducationStatistics.Admin/Services/ReleaseFilesService.cs:line 287
>    at GovUk.Education.ExploreEducationStatistics.Common.Extensions.EitherTaskExtensions.HandleFailuresOrOk[T](Task`1 validationErrorsRaisingAction) in /home/nick/Development/personal/explore-education-statistics/src/GovUk.Education.ExploreEducationStatistics.Common/Extensions/EitherTaskExtensions.cs:line 30
>    at GovUk.Education.ExploreEducationStatistics.Admin.Controllers.Api.ReleasesController.GetDataFilesAsync(Guid releaseId) in /home/nick/Development/personal/explore-education-statistics/src/GovUk.Education.ExploreEducationStatistics.Admin/Controllers/Api/ReleaseController.cs:line 112
>    at lambda_method(Closure , Object )
> ```

This error happens locally due to the test data existing in the DB but not in Azure storage emulator. There is no such problem when running the tests against the dev environment.

This test suite has lots of problems due to differences in test data between different environments. For that reason, to complete this PR, I'll just comment out the majority of the tests so it runs against both local and dev, and then create a ticket to change the analyst_absence_permissions.robot test suite so that it creates its own test data.

2020-08-25 13:27 UTC, ntsim approved these changes

2020-08-26 07:29 UTC, merged