EES-222 Adding test subject files
dfe-analytical-services/explore-education-statistics pull request #1983
Opened 2020-09-08 14:10 UTC by markhiveit

2020-09-08 14:21 UTC, benoutram requested changes

2020-09-08 14:21 UTC, benoutram commented on tests/newman/files/small-files/replace-data/two.meta.csv
> +filter_one,Filter,Filter one,,,,,Filter group one
filter_grouping_column has to be the name of a column name in the data csv file or blank

2020-09-08 14:21 UTC, benoutram commented on tests/newman/files/small-files/replace-data/two_replacement.meta.csv
> +filter_one,Filter,Filter one,,,,,Filter group one
Same problem with filter_grouping_column

2020-09-09 07:58 UTC, markhiveit commented
Marking this as Do not merge as I suspect more test subject might need to be created.

2020-09-09 09:22 UTC, benoutram approved these changes

2020-09-16 07:52 UTC, merged