EES-1626 Trim spaces from subjectTitle
dfe-analytical-services/explore-education-statistics pull request #2226
Opened 2020-12-10 11:09 UTC by markhiveit

2020-12-10 11:26 UTC, luke-h1 approved these changes

2020-12-10 13:24 UTC, ntsim requested changes

2020-12-10 13:24 UTC, ntsim commented on src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataUploadsSection.tsx
> +          name: values.subjectTitle.trim(),
I _think_ there's a `trim` method on `Yup.string`, so it would be good to do this validation client-side before sending these requests off

2020-12-11 11:44 UTC, ntsim approved these changes

2020-12-11 12:40 UTC, merged