EES-1815 Retrieve file names from releaseFile.Name where possible
dfe-analytical-services/explore-education-statistics pull request #2457
Opened 2021-04-01 14:29 UTC by markhiveit

Now that we have releaseFile.Name, we don't need to store subject names
in blob file metadata and can retrieve subject names from releaseFile.Name instead.

This currently is only happening with data files, not ancillary files.

2021-04-01 15:01 UTC, benoutram requested changes

2021-04-01 15:01 UTC, benoutram commented on src/GovUk.Education.ExploreEducationStatistics.Content.Model/Extensions/FileExtensions.cs
> +            var name = "Unknown";
It should never be "Unknown", but see suggestion below

2021-04-07 10:52 UTC, amyb-hiveit approved these changes

2021-04-12 08:57 UTC, benoutram commented
There's a TODO in FileExtensionTests.cs that's been missed, but I think it probably needs to remain if we still rely on the Name field on blobs for Ancillary files? Maybe that comment should be updated to explain why we still set the name on FileInfo from blob properties.

![image](https://user-images.githubusercontent.com/4147126/114368590-74eb7900-9b75-11eb-89b2-34520a46de03.png)

2021-04-12 08:58 UTC, benoutram commented on src/GovUk.Education.ExploreEducationStatistics.Content.Model/Extensions/FileExtensions.cs
> +        public static FileInfo ToFileInfo(this ReleaseFile releaseFile, BlobInfo blobInfo)
I think this should be in ReleaseFileExtensions now which already exists.

2021-04-12 08:58 UTC, benoutram commented on src/GovUk.Education.ExploreEducationStatistics.Content.Model/Extensions/FileExtensions.cs
> +        public static FileInfo ToFileInfo(this MethodologyFile methodologyFile, BlobInfo blobInfo)
There's a MethodologyFileExtensions which this can go in.

2021-04-12 08:59 UTC, benoutram commented on src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Extensions/FileExtensionTests.cs
> +        private readonly ReleaseFile _releaseFile = new ReleaseFile
Everything for ReleaseFile to do with testing GetFileInfo can go in ReleaseFileExtensionTests

2021-04-12 09:01 UTC, benoutram commented on src/GovUk.Education.ExploreEducationStatistics.Content.Model.Tests/Extensions/FileExtensionTests.cs
I don't think anythings been added to test `ToFileInfo(this MethodologyFile)`. That should be added to MethodologyFileExtensionTests

2021-04-14 09:29 UTC, benoutram approved these changes

2021-04-14 11:28 UTC, merged