EES-2028 Remove Name column from Subject
dfe-analytical-services/explore-education-statistics pull request #2480
Opened 2021-04-15 15:36 UTC by markhiveit

2021-04-15 15:40 UTC, luke-h1 approved these changes

2021-04-15 17:08 UTC, luke-h1 requested changes
My bad. I thought this was part of the migration. Aside from the changes Ben has requested everything else looks good to me

2021-04-16 08:55 UTC, benoutram approved these changes

2021-04-16 08:58 UTC, benoutram commented
Added 'do not merge' until we investigate https://dfedigital.atlassian.net/browse/EES-2071

2021-04-16 10:20 UTC, benoutram commented
> Added 'do not merge' until we investigate https://dfedigital.atlassian.net/browse/EES-2071

This is sorted now.

2021-04-16 10:20 UTC, luke-h1 approved these changes

2021-04-16 10:21 UTC, merged