EES-2270 EES-2271 add owner and adopter publications to methodology summary
dfe-analytical-services/explore-education-statistics pull request #2638
Opened 2021-06-30 09:04 UTC by amyb-hiveit

This is hidden under a flag so won't affect the current version,  switch showPublications to true to see it in action.
![Screenshot (24)](https://user-images.githubusercontent.com/81572860/123933061-ede6b980-d989-11eb-9fcd-7ecbb34c40cc.png)

2021-07-07 09:45 UTC, ntsim requested changes

2021-07-07 09:45 UTC, ntsim commented on src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/summary/MethodologySummaryPage.tsx
> +                <SummaryListItem term="Publication">
Might be better to call this 'Owning publication'?

2021-07-07 09:45 UTC, ntsim commented on src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/summary/MethodologySummaryPage.tsx
> +                  <SummaryListItem term="Other publications using this methodology">
This seems like a bit of a mouthful as we're already in the context of a methodology. Would suggest calling this 'Other publications' (combined with the other suggestion for 'Owning publication') instead?

2021-07-07 09:45 UTC, ntsim commented on src/explore-education-statistics-admin/src/services/methodologyService.ts
> +type MethodologyPublication = {
For consistency with the majority of types, would use an interface instead

2021-07-07 09:45 UTC, ntsim commented on src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/summary/MethodologySummaryPage.tsx
> +  const myFakeMethodology = {
Could hoist this variable out of the component scope to save having to build this object on every render

2021-07-07 13:44 UTC, ntsim approved these changes

2021-07-08 08:10 UTC, benoutram approved these changes

2021-07-08 08:10 UTC, merged