EES-2359 Add data guidance text file to 'All files' zip
dfe-analytical-services/explore-education-statistics pull request #2654
Opened 2021-07-06 09:41 UTC by ntsim

This PR adds a new `data-guidance.txt` file to the 'All files' zip. This is essentially just a text version of the metadata guidance file (this will be renamed to data guidance across the frontend in [EES-2235](https://dfedigital.atlassian.net/browse/EES-2235)).

To generate this text file, we leverage the HTML to text converter created in EES-2484.

## Other changes

- Fixed `blockquote` elements in converted text having missing trailing lines.
- Refactored `Startup` files to use a common `StartupUtils.AddPersistenceHelper` util to setup their persistence helpers.

2021-07-07 14:47 UTC, markhiveit commented
I'm getting some unit test failures with this error message. Be interested to see whether other windows users are getting these:
![image](https://user-images.githubusercontent.com/44812484/124780627-a8525f80-df3a-11eb-97f7-96e31937b87e.png)

2021-07-07 16:04 UTC, markhiveit requested changes

2021-07-07 16:06 UTC, markhiveit commented
> I'm getting some unit test failures with this error message. Be interested to see whether other windows users are getting these:
> ![image](https://user-images.githubusercontent.com/44812484/124780627-a8525f80-df3a-11eb-97f7-96e31937b87e.png)

This was due to not being on the latest version of the branch - I checked out EES-2359 rather than ees-2359, and it seems a casesensitivity issue somewhere meant that I could checkout EES-2359, but when pulling from EES-2359 it wouldn't pulled the latest from ees-2359.

2021-07-07 16:11 UTC, ntsim commented on src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/Interfaces/IReleaseService.cs
> +        Task<Release?> GetLatestRelease(Guid publicationId, IEnumerable<Guid> includedReleaseIds);
Good point, I was mostly just looking at the return type in isolation. I'll change it to non-nullable using `Last`.

2021-07-07 16:16 UTC, ntsim commented on src/GovUk.Education.ExploreEducationStatistics.Publisher/Services/ReleaseService.cs
> +            var release = await Find(id);
Think it's probably a better idea to have both I'd say. It's reasonable that there may be a future use-case for it being null, and there isn't any particular harm in having it.

2021-07-07 17:56 UTC, ntsim commented
Do not merge - need to confirm if additional modifications to the 'All files' zip should be made.

2021-07-08 10:36 UTC, markhiveit approved these changes

2021-07-08 11:06 UTC, merged