EES-2498 move methodology page status tags
dfe-analytical-services/explore-education-statistics pull request #2774
Opened 2021-08-11 08:56 UTC by amyb-hiveit

![meth tags](https://user-images.githubusercontent.com/81572860/129000154-f488cfe5-e4d1-427c-9ff0-7048c0a92eb2.png)

Makes the Methodology page more consistent with the Release page by:

- Moving the methodology status and amendment tags to above the tab navigation
- Changing the page caption to 'Amend methodology' instead of 'Edit methodology' when it's an amendment

2021-08-11 10:47 UTC, ntsim requested changes

2021-08-11 10:47 UTC, ntsim commented on src/explore-education-statistics-admin/src/pages/methodology/__tests__/MethodologyPage.test.tsx
> +      expect(screen.getByText('Draft')).toBeInTheDocument();
Could skip the `toBeInTheDocument` as we're asserting the class next (which must be on an existing element) anyway. Similar for the other test cases as well?

2021-08-11 10:47 UTC, ntsim commented on src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/summary/__tests__/MethodologySummaryPage.test.tsx
> -      expect(screen.getByTestId('Status-key')).toHaveTextContent('Status');
Not saying we need to change this with this PR, but I do find these test ids a little gross to look at. 

Would probably be better if we had them as like 'Status - key/value', 'Published on - key/value', etc. Probably one for another day anyway.

2021-08-12 09:20 UTC, ntsim reviewed
Just a few little extra bits and we should be good! :smile:

2021-08-12 10:19 UTC, amyb-hiveit commented on src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/__tests__/MethodologyPage.test.tsx
> +        />
I can't get the tab navigation test to work when change it to use `<Route...`. Any tips?

2021-08-12 10:28 UTC, amyb-hiveit commented on src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/__tests__/MethodologyPage.test.tsx
> +        />
Yeah I did :) The other tests were fine with it, but not the tab changing ones.

2021-08-12 11:10 UTC, ntsim commented on src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/__tests__/MethodologyPage.test.tsx
> +        />
Ah right yeh, it's because we're using the wrong path - `MethologyPage` needs` methodologyRoute.path`!

2021-08-12 12:26 UTC, amyb-hiveit commented on src/explore-education-statistics-admin/src/pages/methodology/edit-methodology/__tests__/MethodologyPage.test.tsx
> +        />
oh yeah :)

2021-08-13 13:21 UTC, ntsim approved these changes

2021-08-13 13:21 UTC, merged