EES-2555 location type in map dropdown label
dfe-analytical-services/explore-education-statistics pull request #2820
Opened 2021-08-26 12:33 UTC by amyb-hiveit

Updates the 'Select a location' dropdown label on maps to show the specific level of location, eg 'Select a Local Authority'. If more than one level is in the dataset then 'Select a location' is shown.

![location](https://user-images.githubusercontent.com/81572860/130963224-75b583ba-e6c7-4801-89b0-af5166365a36.PNG)

2021-08-27 12:52 UTC, markhiveit submitted a review, later dismissed

2021-09-01 09:40 UTC, duncan-at-hiveit requested changes

2021-09-01 09:40 UTC, duncan-at-hiveit commented on src/explore-education-statistics-common/src/modules/charts/components/MapBlockInternal.tsx
> +              label={`2. Select a ${locationType}`}
We should probably switch between "a" and "an" depending on whether or not the locationType starts with a vowel or not

2021-09-02 11:46 UTC, ntsim commented on src/explore-education-statistics-common/src/modules/charts/components/MapBlockInternal.tsx
> +        prefix: 'an',
Not to say that we should - but maybe we could just drop the a/an completely. Seems to me like 'Select English Devolved Area' (for example) sounds fine.

2021-09-06 13:20 UTC, ntsim approved these changes

2021-09-06 13:41 UTC, duncan-at-hiveit approved these changes

2021-09-06 13:42 UTC, merged