EES-2879 - use node 14 across admin & public frontend
dfe-analytical-services/explore-education-statistics pull request #2978
Opened 2021-11-10 11:50 UTC by luke-h1

2021-11-10 13:55 UTC, markhiveit requested changes

2021-11-10 13:55 UTC, markhiveit commented on infrastructure/templates/template.json
> +        "WEBSITE_NODE_DEFAULT_VERSION": "14.0.0",
We should set this to be 14.18.1 - same with other instances.

2021-11-11 10:54 UTC, markhiveit requested changes

2021-11-11 10:54 UTC, markhiveit commented on infrastructure/templates/template.json
> +        "WEBSITE_NODE_DEFAULT_VERSION": "14.18.1",
Seems 14.18.1 isn't on the Azure app servers (or whatever they are). The looking at the service's `api/diagnostics/runtime` it seems "14.16.0" is the latest it has, so we should switch to using that.

2021-11-11 11:32 UTC, ntsim approved these changes

2021-11-11 11:33 UTC, markhiveit approved these changes

2021-11-11 11:33 UTC, merged