EES-2779 group LAs in map dropdown
dfe-analytical-services/explore-education-statistics pull request #3149
Opened 2022-02-03 13:43 UTC by amyb-hiveit

- Groups Local Authorities by region in the Map block location dropdown
- If other location levels are also in the locations then they are grouped by level
- If there are no LAs in the locations then the list is not grouped and remains as it is currently.
- Also changed the 'None selected' option to be added as a placeholder on the FormSelect instead of being added to the options array.

## Screenshots

![groups](https://user-images.githubusercontent.com/81572860/152353934-aaf8cda4-d3b1-40a0-8bee-d8f8950966bd.PNG)

2022-02-07 12:17 UTC, amyb-hiveit commented on src/explore-education-statistics-common/src/modules/charts/components/__tests__/MapBlockInternal.test.tsx
> +describe('MapBlockInternal', () => {
I've moved the tests to be on MapBlockInternal as that's where the code actually is and I've seen an intermittent failure on the first test where it wasn't rendering the map. Probably a long shot but maybe the tests have problems with the dynamic import of MapBlockInternal so have bypassed that.

2022-02-07 12:17 UTC, amyb-hiveit commented on src/explore-education-statistics-common/src/modules/charts/components/__tests__/MapBlockInternal.test.tsx
> +describe('MapBlockInternal', () => {
I've moved the tests to be on MapBlockInternal as that's where the code actually is and I've seen an intermittent failure on the first test where it wasn't rendering the map. Probably a long shot but maybe the tests have problems with the dynamic import of MapBlockInternal so have bypassed that.

2022-02-09 15:46 UTC, ntsim requested changes

2022-02-09 15:46 UTC, ntsim commented on src/explore-education-statistics-common/src/modules/charts/components/__tests__/MapBlockInternal.test.tsx
> +
We should probably do some checks to see if the group labels are correct (and not just the options themselves)

2022-02-09 15:46 UTC, ntsim commented on src/explore-education-statistics-common/src/modules/charts/components/MapBlockInternal.tsx
> +    element => element.filter.level === 'localAuthority',
What about if we have LAD's? They're essentially the same, and we already do this grouping in table tool

2022-02-09 17:13 UTC, amyb-hiveit commented on src/explore-education-statistics-common/src/modules/charts/components/MapBlockInternal.tsx
> +  // If has LAs, group them by region and group any others by level
Not sure what you mean. This is a comment for the code when there are LAs.

2022-02-09 17:15 UTC, ntsim commented on src/explore-education-statistics-common/src/modules/charts/components/MapBlockInternal.tsx
> +  // If has LAs, group them by region and group any others by level
Oh sorry my bad, I actually meant to say 'If there are LAs'

2022-02-10 12:05 UTC, ntsim commented
Looks good, but looks like the build is failing @amyb-hiveit

2022-02-10 16:34 UTC, ntsim approved these changes

2022-02-11 10:20 UTC, merged