EES-3281 Fix chart reference line position labels
dfe-analytical-services/explore-education-statistics pull request #3280
Opened 2022-05-03 15:47 UTC by ntsim

This PR fixes the position labels displayed for chart reference lines in axis configuration. Previously, these would show the underlying filter id/value instead of the human-readable label.

## Related changes

- Updated reference lines to be more visible. Previously, these were essentially invisible to users as they had no clear visual differences from other lines on charts. We've now made reference lines darker, dashed and wider to make them stand out.
- Added filtering to remove reference line position options on the major axis. We want to avoid having reference lines for options that are no longer valid (e.g. the user changes the data sets or the axis `groupBy`).
- Added a remediation to prevent stale state being sent to the server when chart builder is saved. Note that this is not a complete solution and it would be better to revisit state management across chart builder to make this better. See [EES-3355](https://dfedigital.atlassian.net/browse/EES-3355) for details.

## Screenshots

Human-readable reference line position labels:

![image](https://user-images.githubusercontent.com/9917868/166486797-5928c593-1e3a-4e3f-87cd-6cc128ec5ccf.png)

More visible reference lines:

![image](https://user-images.githubusercontent.com/9917868/166486287-fc759717-ef72-4707-ac3c-7e67cfef1545.png)

2022-05-04 12:53 UTC, amyb-hiveit requested changes
Looks good, just a few small comments. Definitely agree about revisiting the chart builder state management.

2022-05-05 12:04 UTC, ntsim commented on src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartReferenceLinesConfiguration.tsx
> +          <th />
Good point! The entire thing was just copy and pasted from the parent component. The header is now 'Actions'

2022-05-19 13:31 UTC, ntsim commented on src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartReferenceLinesConfiguration.tsx
> +                disabled={!referenceLine.position || !referenceLine.label}
I've gone one step further and refactored the add line form to use Formik. Validation errors are now shown inline with the form inputs, and we also show a tooltip and aria-disable the button when the form is invalid.

This should hopefully provide much better feedback than we were previously.

2022-05-23 09:27 UTC, amyb-hiveit commented on src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartReferenceLinesConfiguration.tsx
> +                disabled={!referenceLine.position || !referenceLine.label}
Nice, thanks.

2022-05-23 09:27 UTC, amyb-hiveit approved these changes

2022-05-23 09:28 UTC, merged