EES-3464 - update UI tests to be able to use keycloak
dfe-analytical-services/explore-education-statistics pull request #3335
Opened 2022-06-17 11:39 UTC by luke-h1

This PR: 
- updates the UI tests to be able to use Keycloak as an identity provider. Users can opt-in to use a keycloak-based identity provider by setting the following variable in a `.env` file: 

```
IDENTITY_PROVIDER= 
# 'AZURE' or 'KEYCLOAK'
```

Note: 
- If you don't wish to edit your existing `.env.local` you can pass create a custom `.env` in order for the tests to load a custom `.env` file instead of the default (`.env.local`). The `-e` flag can then be passed in order to specify that you want to test against a local environment with Keycloak

2022-06-17 12:34 UTC, markhiveit requested changes

2022-06-17 12:34 UTC, markhiveit commented on tests/robot-tests/scripts/get_auth_tokens.py
>          try:
You could pull some of this code into functions to make the provider logic possible to read at a glance. Something like:
```
if id_provider == KEYCLOAK:
  login_with_keycloak(driver, url, email, password, whatever else)
elseif id_provider == AZURE:
  login_with_azure(...)
else:
  throw exception
```

2022-06-20 10:58 UTC, duncan-at-hiveit approved these changes

2022-06-20 10:58 UTC, duncan-at-hiveit commented on tests/robot-tests/.env.example
> +IDENTITY_PROVIDER= # ("AZURE" or "KEYCLOAK") opt into using either a Keycloak or Azure based identity provider
We normally provide defaults in this example file - wondering if we should just add AZURE here as a default?

2022-06-20 10:59 UTC, duncan-at-hiveit approved these changes

2022-06-20 10:59 UTC, merged