EES-3225 publication team access page
dfe-analytical-services/explore-education-statistics pull request #3418
Opened 2022-08-01 15:38 UTC by amyb-hiveit

Adds the Team Access section to Manage Publication, including the Invite new user and Manage release contributors pages. 

This work will be hidden to users until it's all ready, so for this you can only access the new page directly, at /publication/<id>/team, there are no links to it yet.

I've made some changes to existing components that will be visible in the current version but I figured these were small enough changed that it wasn't worth having them under a flag:
- added a table header and changed the remove button text in ReleaseContributorTable
- reduced the size of the checkboxes on the invite user and manage contributors forms

Other notes:
- I've renamed some files that are used here and in the current version so the naming makes more sense for both
- I added `live` to ReleaseSummary as was missing from the type
- I've updated the existing UI tests, but not added new ones (those will be done when this work is ready to go live)

![team](https://user-images.githubusercontent.com/81572860/182183202-fac7e585-f85b-43e3-a1a0-669a11421ac0.PNG)

2022-08-04 12:26 UTC, ntsim requested changes

2022-08-04 12:26 UTC, ntsim commented on src/explore-education-statistics-admin/src/pages/publication/components/__tests__/PublicationManageTeamAccess.test.tsx
> +      ).toBeInTheDocument();
Don't use `getByRole` selectors (and variants) in `waitFor`. Use faster selectors like `getByText` within the `waitFor` and then perform `getByRole` after it has completed.

2022-08-04 12:26 UTC, ntsim commented on src/explore-education-statistics-admin/src/services/releaseService.ts
> +  live?: boolean;
This is optional? Would have expected it to non-optional. Sounds like a potential bug in the backend. Probably needs a ticket to sort out if so.

2022-08-08 11:15 UTC, amyb-hiveit commented on src/explore-education-statistics-admin/src/pages/publication/PublicationTeamAccessPage.tsx
> +            label="Select release"
It's managed at both levels:
- 'Invite new users' is at the publication level. You invite a user to have access to all or some of the releases in the publication.
- 'Add or remove users' is on the release level. You're adding/removing users (who already have access to some releases in the publication) to the selected release.

I've had a chat with Marv about this. It was user tested when it was done originally (not that long ago) so he's going to look through the notes from that and decide how to make it clearer, especially the 'Invite new users' button. I'll raise a new ticket under the main dashboard story for this so it'll get done before the work is released.

2022-08-08 14:11 UTC, ntsim approved these changes

2022-08-08 14:27 UTC, merged