EES-3899 EES-3906 fixes for charts with negative values
dfe-analytical-services/explore-education-statistics pull request #3660
Opened 2022-11-24 12:41 UTC by amyb-hiveit

Fixes the following problems for charts with negative values:
- EES-3899 Charts with negative values should have a line at 0 on the minor axis (note that while the line now shows at 0, there won't always be a zero tick point as this depends on how the tick spacing is generated)
- EES-3906 data labels on bar charts positioned 'inside' were on the wrong place 
- negative minimum values in the minor axis domain weren't rounded to 'nice' values like max values are, resulting in non rounded tick points

Before:
![chart-neg-dev](https://user-images.githubusercontent.com/81572860/203786210-5690a431-9c7d-424e-9908-fd580d39d9c4.PNG)

Now:
![chart-neg-pr](https://user-images.githubusercontent.com/81572860/203786208-34c5465c-4987-43a7-8c6c-20d0b4592760.PNG)

2022-11-24 18:06 UTC, ntsim requested changes

2022-11-28 12:04 UTC, amyb-hiveit commented on src/explore-education-statistics-common/src/modules/charts/components/HorizontalBarBlock.tsx
> +function getDataLabelPosition({
Cool, I've moved them.

2022-11-28 12:06 UTC, amyb-hiveit commented on src/explore-education-statistics-common/src/modules/charts/util/domainTicks.ts
> + * - if it's negative round down to one significant figure and return the next 'nice' value (even or starting with 5)
Yeah... I did wonder. I considered changing it a bit, but figured there should be a conversation about what would be best first. At least now it's tested and commented we'll know what it's currently doing :)

2022-11-28 12:07 UTC, amyb-hiveit commented on src/explore-education-statistics-common/src/modules/charts/components/HorizontalBarBlock.tsx
> +  return dataLabelPosition === 'inside' ? 'right' : 'insideRight';
I'll add a ticket for it.

2022-11-29 11:35 UTC, ntsim approved these changes

2022-11-30 09:11 UTC, merged