EES-3399 UI test to Amend then cancel an amendment, check if the content is intact
dfe-analytical-services/explore-education-statistics pull request #3870
Opened 2023-02-02 11:25 UTC by N-moh

UI test to check if all the content remains intact after making changes to release summary, replace data, edit data block, edit footnotes etc, then cancel amendment.
![Screenshot (74)](https://user-images.githubusercontent.com/93383553/216306216-eb2f7cd5-7790-4100-a97c-5a9a945229c2.png)

2023-02-02 15:01 UTC, duncan-at-hiveit commented on tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_cancel.robot
> +    user checks infographic chart contains alt    id:chartBuilderPreview    Sample alt text
Given that we're not changing the chart config as part of creating the amendment, I'd probably cut this part of the test out, as I don't think that it's adding much to the test case. I could be wrong! smile

2023-02-02 15:03 UTC, duncan-at-hiveit commented on tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_cancel.robot
> +    user checks headed table body row contains    Data file size    17 Kb    wait=%{WAIT_SMALL}
I would cut these verification lines out

2023-02-02 15:07 UTC, duncan-at-hiveit commented on tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_cancel.robot
> +    user checks headed table body row cell contains    Status    2    Complete    wait=%{WAIT_LONG}
I'd cut these out too

2023-02-02 15:08 UTC, duncan-at-hiveit commented on tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_cancel.robot
> +    user checks headed table body row cell contains    Proportion of settings open    1    1%
I'd cut these out too

2023-02-02 15:10 UTC, duncan-at-hiveit commented on tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_cancel.robot
> +Navigate to the 'Content' page to check if its intact
I'd maybe rename this to:

`Verify that the Release content is unchanged`

2023-02-02 15:12 UTC, duncan-at-hiveit commented on tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_cancel.robot
> +Verify pre existing footnotes
I'd maybe rename this to:

`Verify that the footnotes are unchanged`

2023-02-02 15:13 UTC, duncan-at-hiveit commented on tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_cancel.robot
> +Verify Test text accordion section contains correct text as before
I'd maybe rename this to:

`Verify that the Test text accordion is unchanged`

2023-02-02 15:14 UTC, duncan-at-hiveit commented on tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_cancel.robot
> +    user checks summary list contains    Time period    2020 Week 13 to 2021 Week 24
(as the same use case is covered in another test already)

2023-02-02 15:14 UTC, duncan-at-hiveit commented on tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_cancel.robot
> +    user checks summary list contains    File size    12 B    ${section_1}
(as the same use case is covered in another test already)

2023-02-02 15:14 UTC, duncan-at-hiveit commented on tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_cancel.robot
> +    user checks headed table body row contains    Data file size    17 Kb    wait=%{WAIT_SMALL}
(as the same use case is covered in another test already)

2023-02-02 15:14 UTC, duncan-at-hiveit commented on tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_cancel.robot
> +    user checks headed table body row cell contains    Status    2    Complete    wait=%{WAIT_LONG}
(as the same use case is covered in another test already)

2023-02-07 10:50 UTC, luke-h1 requested changes

2023-02-07 10:50 UTC, luke-h1 commented on tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_and_cancel.robot
> +Verify that the Dates data block table has footnotes are unchanged
```suggestion
Verify that the Dates data block table footnotes are unchanged
```

2023-02-07 10:50 UTC, luke-h1 commented on tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_and_cancel.robot
> +Verify that the Embedded URL accordian section is unchanged
```suggestion
Verify that the Embedded URL accordion section is unchanged
```

2023-02-07 10:50 UTC, luke-h1 commented on tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_and_cancel.robot
> +Verify that the Release content is unchanged
```suggestion
Verify that release content is unchanged
```

2023-02-07 10:50 UTC, luke-h1 commented on tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_and_cancel.robot
> +User navigates to Data blocks page
```suggestion
Navigate to Data blocks page
```

2023-02-07 10:50 UTC, luke-h1 commented on tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_and_cancel.robot
> +Return to Admin and Create amendment
```suggestion
Return to Admin and create amendment
```

2023-02-07 10:50 UTC, luke-h1 commented on tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_and_cancel.robot
> +    user waits until h1 is visible    ${PUBLICATION_NAME}    %{WAIT_MEDIUM}
```suggestion
    user waits until h1 is visible    ${PUBLICATION_NAME}    %{WAIT_SMALL}
```

2023-02-07 10:50 UTC, luke-h1 commented on tests/robot-tests/tests/admin_and_public_2/bau/publish_amend_and_cancel.robot
> +Create new publication for "UI tests topic" topic
```suggestion
Create new publication and release via API
```

2023-02-07 10:53 UTC, luke-h1 commented
Not too keen on the convention of using `Changes in response to PR comments` as a commit message. It doesn't really explain what PR comments or changes we've made. I'd suggest either rebasing to one commit or leaving a message such as `EES-xxxx - renamed variables and refactored x` (dependening on what you've changed of course)

2023-02-07 19:29 UTC, luke-h1 approved these changes

2023-02-08 15:10 UTC, closed without merging