EES-4450 fix table rendering when data is missing
dfe-analytical-services/explore-education-statistics pull request #4213
Opened 2023-07-31 16:03 UTC by amyb-hiveit

The permalink migration testing exposed problems caused by our earlier table fixes in https://github.com/dfe-analytical-services/explore-education-statistics/pull/4110

Row headers were rendering incorrectly when:
- there are collapsed cells (because of duplicate labels), and
- there is missing data so rows are excluded from the table

There didn't seem to be any problems with these for column headers, but I've added test cases for them as well just in case.

2023-08-02 17:52 UTC, ntsim requested changes

2023-08-02 17:52 UTC, ntsim commented on src/explore-education-statistics-common/src/modules/table-tool/utils/createExpandedRowHeaders.ts
> +        );
By flatting the `collapsibleLevels` array, we can simplify this to:

```ts
const isCollapsibleLevel = collapsibleLevels[depth];
```

2023-08-03 08:21 UTC, amyb-hiveit commented on src/explore-education-statistics-common/src/modules/table-tool/utils/createExpandedRowHeaders.ts
> +  const { maxDepth, rowHeadersCollapsibleLevels } = rowHeadersInfo;
Cheers Nick, that's done now.

2023-08-03 08:58 UTC, ntsim approved these changes

2023-08-03 09:06 UTC, merged