EES-3353 label width option for ref lines and make editable
dfe-analytical-services/explore-education-statistics pull request #4266
Opened 2023-08-30 09:51 UTC by amyb-hiveit

Adds new functionality to chart reference lines:

1. Ability to set a label width so that reference line labels will wrap onto multiple lines
- uses Recharts' `Text` component which has a `width` property (note that this only wraps words, it doesn't break long words)
- existing lines will be unaffected

2. Ability to edit reference lines
- because is was really annoying that you couldn't 
- while editing a line it prevents editing others and hides the add form as it looked really messy when had multiple forms open at once.

![refline1](https://github.com/dfe-analytical-services/explore-education-statistics/assets/81572860/072066b3-8792-4fb7-bfae-1e2921427d6d)
![refline2](https://github.com/dfe-analytical-services/explore-education-statistics/assets/81572860/c29a1323-619e-42ca-a148-eead1bb96e8c)

2023-09-05 10:23 UTC, ntsim requested changes

2023-09-06 08:30 UTC, amyb-hiveit commented on src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartReferenceLineConfiguration.tsx
> +                  ariaDisabled={disableEditing}
I've removed them instead of disabling.

2023-09-06 08:33 UTC, amyb-hiveit commented on src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartReferenceLineConfiguration.tsx
> +            )}
I've split it out as you suggest.

2023-09-06 08:34 UTC, amyb-hiveit commented on src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartReferenceLineConfiguration.tsx
> +    <Formik<FormValues>
As discussed, I've left it using Formik for now.  I've updated the validation schema as you suggest.

2023-09-06 08:36 UTC, amyb-hiveit commented on src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartReferenceLinesConfiguration.tsx
> +  }) => void;
I've changed it to `onChange` and use it instead of `onRemove` as well.

2023-09-06 08:36 UTC, amyb-hiveit commented on src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartReferenceLineConfiguration.tsx
> +  referenceLines: ReferenceLine[];
I've gone for changing `referenceLines` to `allReferenceLines`.

2023-09-06 14:30 UTC, ntsim approved these changes
Left one minor comment, but approved otherwise

2023-09-07 08:51 UTC, ntsim commented on src/explore-education-statistics-admin/src/pages/release/datablocks/components/chart/ChartReferenceLineConfigurationForm.tsx
> +  style: ReferenceLineStyle;
Could alphabetise this

2023-09-07 10:33 UTC, merged