DRAFT: EES-4624 add official statistics in development release type
dfe-analytical-services/explore-education-statistics pull request #4391
Opened 2023-11-02 17:12 UTC by amyb-hiveit

**Draft: waiting on some text for `FilterModal` and for the backend validation.**

Adds a new release type 'Official statistics in development':
- for new releases this replaces 'Experimental statistics' which will no longer be an option when creating a release
- the release type for existing  'Experimental statistics' releases does not change and it is still an option when they are edited.

Also:
- converted `ReleaseSummaryForm` to React Hook Form and did some tidying around this
- slightly annoyingly I ended up having to create a RHF version of `FormNumberInput` because of `value={!value && value !== 0 ? '' : value}` on the original which makes the input unusable in RHF and stuff breaks without it in Formik forms.

2023-11-07 14:28 UTC, ntsim requested changes

2023-11-07 14:28 UTC, ntsim commented on src/explore-education-statistics-common/src/components/form/rhf/RHFFormNumberInput.tsx
> +export default function RHFFormNumberInput(props: RHFFormNumberInputProps) {
Given this'll only really get used by the form field component, probably worth just throwing this in the same file as `RHFFormFieldNumberInput` and not exporting it (same for the props)

2023-11-07 14:32 UTC, amyb-hiveit commented on src/explore-education-statistics-admin/src/pages/release/ReleaseCreatePage.tsx
> +  const { value: model, isLoading } = useAsyncRetry<Model>(async () => {
I did consider converting to to React Query but decided converting the form to RHF was enough refactoring for one PR (in the spirit of trying to keep PRs a bit smaller and quicker to review).

2023-11-08 12:16 UTC, ntsim commented on src/explore-education-statistics-admin/src/pages/release/ReleaseCreatePage.tsx
> +  const { value: model, isLoading } = useAsyncRetry<Model>(async () => {
Fair enough! Do you want to do a follow up PR on the heels of this one, or leave it for another time?

2023-11-08 12:16 UTC, ntsim approved these changes

2023-11-08 12:25 UTC, amyb-hiveit commented on src/explore-education-statistics-admin/src/pages/release/ReleaseCreatePage.tsx
> +  const { value: model, isLoading } = useAsyncRetry<Model>(async () => {
I'm going to leave it for another time as in the middle of something else now. But I'm going to have a chat to Cam about getting more of a plan for doing the incremental updates for this and RHF.

2023-11-23 08:43 UTC, duncan-at-hiveit approved these changes

2023-11-23 09:07 UTC, merged