EES-4708 Adding an endpoint to retrieve a summary for a single Data Set
dfe-analytical-services/explore-education-statistics pull request #4577
Opened 2024-02-12 15:41 UTC by jack-hive

2024-02-13 12:22 UTC, ntsim requested changes

2024-02-13 12:22 UTC, ntsim commented on src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.Tests/Controllers/DataSetsControllerTests.cs
> +                .Generate();
Don't have to do this, but you can actually use the generator's implicit conversion so we don't have to call `Generate` explicitly i.e.

```cs
DataSet dataSet = DataFixture
   .DefaultDataSet()
   .WithStatus(dataSetStatus);
```

Personally, I'm not particularly bothered either way, but it's something I've seen Ben doing a bit of so thought I'd mention it. Feel free to do whatever you'd prefer!

A similar thing could apply anytime we're calling `Generate`. Note this doesn't apply for `GenerateList` or `GenerateArray` variants where we should still use `var`.

Whatever we go with, we'll want to be consistent across all our tests we've written so far.

2024-02-14 11:06 UTC, jack-hive commented on src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/DataSetService.cs
> +            : dataSet;
I used `SingleOrNotFound()` instead. These are nice extensions!

2024-02-14 11:26 UTC, ntsim commented on src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Services/DataSetService.cs
> +            : dataSet;
Nice one, didn't even know about this!

2024-02-14 11:27 UTC, ntsim approved these changes

2024-02-14 11:28 UTC, merged