EES- 4822/Use 301 for Redirects
dfe-analytical-services/explore-education-statistics pull request #4610
Opened 2024-03-01 08:06 UTC by sambiramairelogic

This PR reconfigures the public site to redirect using HTTP Status Code 301 rather than 308. 

NextJS uses Http Status 308 for permanent redirects, as oppose to the usual 301. This is a deliberate design choice as 308s preserve the HTTP Verb when redirecting, however 301s turn everything to a GET. Unfortunately, NextJS does not provide a configuration option to use 301s instead. Luckily, we are using a custom server, so we are able to configure redirects in Express JS before reaching Next at all. 

By default, Next sets the [trailingSlash](https://nextjs.org/docs/app/api-reference/next-config-js/trailingSlash) config to false, meaning urls ending with slashes get redirected with the slash curtailed. This behaviour is re-created in `server.js` with the 301 status code. 

We also have two manual redirects, `meta-guidance` -> `data-guidance` and `download-latest-data` -> `data-catalogue`. These ideally need to be removed, however Google has trawled them within the past 6 months so I don't believe we can just yet. For now, these have also been re-created using 301s. 

New robot tests have been added to verify that these redirects still perform correctly, although sadly I don't believe robot can assert on which status code was used for the redirect. 

Exactly the same tests like-for-like have been created in Playwright as an experiment (spoiler alert: the playwright tests were SO much easier and took less than a quarter of the time...)

2024-03-01 08:08 UTC, sambiramairelogic commented on src/explore-education-statistics-frontend/server.js
> +  }
I very much confess that this abstraction is quite noddy - but technically the "rule of three" applies! :D 

Very happy to revert to repeated lines if anyone feels strongly

2024-03-01 08:14 UTC, sambiramairelogic commented on src/explore-education-statistics-frontend/server.js
> +    nextNotShadowed();
If anyone can come up with a better name for this, be my guest. 

This method is ExpressJS' callback to just "go onto the next thing", which they call `next` by default. This is however shadowed if you import `next` (as in NextJS) above! I considered `continue` or `nextMiddleware` or `proceed` but for obvious reasons they're also problematic 🤷

2024-03-01 15:00 UTC, mmyoungman requested changes

2024-03-01 15:09 UTC, sambiramairelogic commented on tests/robot-tests/tests/libs/public-utilities.py
> +def browser_should_be_at_address(expected):
Aha, I hadn't realised. Will change :)

2024-03-01 15:59 UTC, mmyoungman approved these changes
The `server.js` changes look straightforward and I struggle to imagine what could be wrong with them, but I've hardly ever looked at Express so would suggest someone else taking a look before merging.

2024-03-04 11:35 UTC, amyb-hiveit approved these changes
LGTM 👍

2024-03-05 12:15 UTC, sambiramairelogic commented
<img width="1913" alt="Benchmark on Dev" src="https://github.com/dfe-analytical-services/explore-education-statistics/assets/63285990/f9557cbf-1843-45c4-bfa2-57134f82db7a">
<img width="1910" alt="With301Redirects" src="https://github.com/dfe-analytical-services/explore-education-statistics/assets/63285990/4b71101e-a7cf-4269-ba47-e72142fcfa3e">

2024-03-05 12:16 UTC, merged