EES-4716 Part 4 - Add stub data set query GET endpoint, Parquet path resolver and restructured locations meta
dfe-analytical-services/explore-education-statistics pull request #4679
Opened 2024-03-20 13:24 UTC by ntsim

This PR:

- Adds a stub for the data query GET endpoint (`QueryDataSetGet`) so integration test writing can commence (EES-5015)
- Adds `ParquetPathResolver` service that can allow us to resolve paths to Parquet files based on the current environment (and any configured option).
- Restructures the locations Parquet meta into a single location table. This is necessary to simplify data set queries as having different tables over-complicates things.
- Refactors the seeder to use Parquet table refs to make refactoring column names easier in the future.

Note that the `ParquetPathResolver` hasn't necessarily been completed for integration tests yet. This has been left for the testing ticket to finalise (EES-5015).

2024-03-20 15:50 UTC, jack-hive requested changes

2024-03-20 15:50 UTC, jack-hive commented on src/GovUk.Education.ExploreEducationStatistics.Public.Data.Services/Options/ParquetFilesOptions.cs
> +using System.ComponentModel.DataAnnotations;
Can remove this `using`

2024-03-20 18:17 UTC, jack-hive requested changes

2024-03-20 18:18 UTC, jack-hive commented on src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Parquet/Tables/DataTable.cs
> +    public static readonly TableRef DefaultRef = new(TableName);
On revisiting this, I'm happy with it being left `public`. Just found it weird that we have two ways to access the same thing at first.

2024-03-20 22:23 UTC, ntsim commented on src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/Controllers/DataSetsController.cs
> +    ///
I've adjusted the preceding paragraph which specifies this caveat.

2024-03-20 22:28 UTC, ntsim commented on src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/ViewModels/DataSetQueryResultViewModels.cs
> +    public required Dictionary<string, string> Locations { get; init; }
Nope, the locations will be in different levels as rows look like this:

country_name | country_code | region_name | region_code | the_rest_of_the_data 
-------------|--------------|-------------| ----------- | --------------------
England      | E00000001    | Yorkshire   | E00000002   | ..... 

So the corresponding JSON result would need to look something like this:

```json
{
  "locations": {
     "NAT": "id of England"
     "REG": "id of Yorkshire"
  }
}
```

Where the different dictionary values will be different depending on where the data was colelcted.

2024-03-20 22:30 UTC, ntsim commented on src/GovUk.Education.ExploreEducationStatistics.Public.Data.Model/Parquet/Tables/DataTable.cs
> +    public static readonly TableRef DefaultRef = new(TableName);
I've just changed them all to private as the default refs don't need to be exposed really

2024-03-21 10:52 UTC, jack-hive approved these changes
Nice!

2024-03-21 10:52 UTC, jack-hive commented on src/GovUk.Education.ExploreEducationStatistics.Public.Data.Api/ViewModels/DataSetQueryResultViewModels.cs
> +    public required Dictionary<string, string> Locations { get; init; }
Sorry, I understand this now. Makes sense! At first glance it always messes with my thought process when I see geographic level appearing in multiple places

2024-03-21 11:34 UTC, merged