EES-5115 - Filter Option mapping endpoint
dfe-analytical-services/explore-education-statistics pull request #5028
Opened 2024-07-03 14:32 UTC by duncan-at-hiveit

This PR:
- adds an endpoint for updating the mappings for Filter Options via a debounced autosave mechansim.

Much the same as the PR for autosaving Location mappings!

2024-07-04 10:44 UTC, jack-hive requested changes

2024-07-04 10:44 UTC, jack-hive commented on src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Public.Data/BatchMappingUpdateViewModels.cs
I think you can remove the `.NotNull()` on the `FilterOptionMappingUpdateRequest.Validator` as the `.NotEmpty()` covers it

**I also think the changes in 5114 were intended to be here**

2024-07-04 10:44 UTC, jack-hive commented on src/GovUk.Education.ExploreEducationStatistics.Admin.Tests/Controllers/Api/Public.Data/DataSetVersionMappingControllerTests.cs
> +                    CandidateKey = "target-filter-option-1-key"
I've just realised, we don't have anything in the code which validates that the candidate key selected is a legitimate candidate key. Should we validate it against the list of candidate keys in the mapping plan?

2024-07-04 10:44 UTC, jack-hive commented on src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Public.Data/BatchMappingUpdateViewModels.cs
I think you can get rid of the nullable types `string?` and `MappingType?` on the `Type` and `SourceKey`, respectively, in `MappingUpdateRequest`

2024-07-05 12:40 UTC, duncan-at-hiveit commented on src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Public.Data/BatchMappingUpdateViewModels.cs
I've removed the nullable string types but left the enum types as nullable, otherwise they're auto-bound to the first value within their enum if left empty.

2024-07-08 11:05 UTC, jack-hive commented on src/GovUk.Education.ExploreEducationStatistics.Admin/ViewModels/Public.Data/BatchMappingUpdateViewModels.cs
makes sense!

2024-07-08 11:08 UTC, jack-hive commented
I think this might need rebasing back onto 5111 again, as it looks like a commit from EES-5111 has snuck in?

2024-07-08 11:13 UTC, jack-hive approved these changes

2024-07-08 11:21 UTC, merged