EES-4382 api data set history page
dfe-analytical-services/explore-education-statistics pull request #5164
Opened 2024-08-19 16:11 UTC by amyb-hiveit

Adds the API data set history page in the admin. There are some TODOs pending a back end change (EES-5427).

The ticket doesn't mention pagination, but since the endpoint is paginated I thought I might as well add it in as it was quick to do.

![Screenshot 2024-08-19 170812](https://github.com/user-attachments/assets/a1494943-cce3-4669-bf87-c87b708b0eba)

2024-08-20 11:03 UTC, ntsim requested changes

2024-08-20 11:03 UTC, ntsim commented on src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetHistoryPage.tsx
> +                      <td>{dataSetVersion.releaseVersion.title}</td>
Would suggest that we also link to the release for convenience

2024-08-20 11:09 UTC, ntsim commented on src/explore-education-statistics-admin/src/services/apiDataSetVersionService.ts
> +    dataSetVersionId: string,
This should be `dataSetId`

2024-08-20 11:09 UTC, ntsim commented on src/explore-education-statistics-admin/src/queries/apiDataSetVersionQueries.ts
> +  list(dataSetVersionId: string, query?: ListVersionsParams) {
This should be `dataSetId`

2024-08-20 11:11 UTC, ntsim commented on src/explore-education-statistics-admin/src/services/apiDataSetVersionService.ts
> +    return client.get(`/public-data/data-set-versions/${dataSetVersionId}`, {
This URL is really confusing! I'll put a change in to fix this

2024-08-21 11:25 UTC, amyb-hiveit commented on src/explore-education-statistics-admin/src/pages/release/data/ReleaseApiDataSetHistoryPage.tsx
> +              />
Yep good point, I've changed it to links.

2024-08-21 13:24 UTC, ntsim approved these changes

2024-08-21 13:27 UTC, merged