EES-5542 Maps fetching/rendering boundaries for datasets
dfe-analytical-services/explore-education-statistics pull request #5423
Opened 2024-11-28 17:39 UTC by bennettstuart

Setting map charts to fetch location geo JSON for data sets with boundary levels set

2024-12-11 10:59 UTC, ntsim commented on src/explore-education-statistics-common/src/modules/charts/components/ChartRenderer.tsx
> +  dataBlockParentId?: string;
As discussed - if the callback approach works, we shouldn't need these parameters

2024-12-13 10:28 UTC, bennettstuart commented on src/explore-education-statistics-common/src/modules/charts/components/__tests__/MapBlock.test.tsx
> -      // expect(paths[3]).toHaveAttribute('fill', '#003078');
On second thought, ignore me - think I've misunderstood, I'll look into rectifying this

2024-12-18 12:16 UTC, bennettstuart commented on src/explore-education-statistics-common/src/modules/charts/components/__tests__/MapBlock.test.tsx
> -      // expect(paths[3]).toHaveAttribute('fill', '#003078');
on third thought, yeah changing selected data set doesn't directly alter polygons, that would have to be tested in an integration test

2024-12-19 14:12 UTC, bennettstuart commented on src/explore-education-statistics-common/src/modules/charts/components/__tests__/MapBlock.test.tsx
> -      // expect(paths[3]).toHaveAttribute('fill', '#003078');
I've added an integration test for the above, and referenced it to be completed in the ticket that will re-enable the map testing

2025-01-07 14:37 UTC, ntsim requested changes
Looks like some of your tests are failing as well. Seems like there's some errors around a missing intersection observer. 

I've added the `intersection-observer` polyfill to fix this in the #5502 PR (which fixes the `react-leaflet` problem) that is targeting your branch.

2025-01-07 14:37 UTC, ntsim commented on src/explore-education-statistics-common/src/modules/find-statistics/components/__tests__/DataBlockTabs.test.tsx
> +  // EES-4902 react-leaflet now uses ESM so unable to test this currently
As mentioned in another comment - I've created a little PR to your branch with the react-leaflet fix #5502 

We should now be able to update this test to work correctly.

2025-01-07 14:37 UTC, ntsim commented on src/explore-education-statistics-common/src/modules/find-statistics/components/__tests__/DataBlockTabs.test.tsx
> +    expect(tableBuilderService.getDataBlockTableData).toHaveBeenCalledTimes(1);
Would be consistent with the rest of the test code use the `toBeCalledTimes` method

2025-01-07 14:37 UTC, ntsim commented on src/explore-education-statistics-common/src/modules/find-statistics/components/__tests__/DataBlockTabs.test.tsx
> +    expect(tableBuilderService.getLocationGeoJson).toHaveBeenCalledTimes(2);
As above - would use `toBeCalledTimes` for consistency

2025-01-07 14:37 UTC, ntsim commented on src/explore-education-statistics-common/src/modules/find-statistics/components/__tests__/DataBlockTabs.test.tsx
> +      expect(tableBuilderService.getLocationGeoJson).toBeCalled();
This is redundant - we're doing `toBeCalledTimes(1)` below

2025-01-07 14:37 UTC, ntsim commented on src/explore-education-statistics-common/src/modules/find-statistics/components/__tests__/DataBlockTabs.test.tsx
> +    });
Can replace with `findByLabelText`

2025-01-07 14:37 UTC, ntsim commented on src/explore-education-statistics-common/src/modules/find-statistics/components/__tests__/DataBlockTabs.test.tsx
> +    const dataSetOptions = within(dataSetSelectInput).getAllByRole('option');
As other places - could simplify these variable names to `select` and `options` respectively

2025-01-20 10:21 UTC, bennettstuart commented on src/explore-education-statistics-common/src/modules/find-statistics/components/DataBlockTabs.tsx
> +                        {...commonChartProps}
Can't say I've resolved this as the landscape has slightly changed so I'd be interested to hear your thoughts (I've made ChartRendererProps now have a `chart` prop instead of extend Chart)

2025-01-20 10:22 UTC, bennettstuart commented on src/explore-education-statistics-common/src/modules/find-statistics/components/DataBlockTabs.tsx
> +                  const commonChartProps = {
Same as https://github.com/dfe-analytical-services/explore-education-statistics/pull/5423#discussion_r1922157084

2025-01-20 10:27 UTC, bennettstuart commented on src/explore-education-statistics-common/src/modules/charts/components/__tests__/MapBlock.test.tsx
> +    });
The loading spinner won't appear initially, as the chart is loaded with location data.
for this unit test, I'm not sure how to go about testing `onBoundaryLevelChange` as this could happen outside of this component.
I've added tests for differing map paths after changing data set in DataBlockTabs.test.tsx : `selecting data set with boundaryLevel retrieves and renders new map polygons`

2025-01-22 01:17 UTC, ntsim commented on src/explore-education-statistics-common/src/modules/find-statistics/components/DataBlockTabs.tsx
> +                          meta: fullTable?.subjectMeta,
`fullTable` should be defined so don't need optional chaining. Same applies in other places below as well.

2025-01-22 01:17 UTC, ntsim commented on src/explore-education-statistics-common/src/modules/find-statistics/components/DataBlockTabs.tsx
> +            {!!tableDataError && errorMessage}
Don't need this if we display the `errorMessage` if `isTableDataError` is true before the tabs render (see earlier comment).

2025-01-24 15:51 UTC, bennettstuart commented on src/explore-education-statistics-common/src/modules/find-statistics/components/__tests__/DataBlockTabs.test.tsx
> +    expect(updatedPaths[1]).toHaveAttribute('d', 'M0 0');
Jest doesn't render the map with any size, so all polygons are either fully covering the screen, or not render due to not being in the map 'window' because of this we decided to go with a more simple test that checks we have the same number of `path`s after requesting new geoJson

2025-01-27 16:19 UTC, bennettstuart commented on src/explore-education-statistics-common/src/services/types/blocks.ts
> +  | VerticalBarChart;
I've had a go at tidying up the chart types, hopefully it's improved, think we're pushing typescript to it's limit or not using it in the correct way in some places, see what you think and let me know if you want to go through it

2025-02-03 13:17 UTC, ntsim approved these changes

2025-02-03 13:45 UTC, merged