EES-5544 Change data set import page accordions into a table
dfe-analytical-services/explore-education-statistics pull request #5459
Opened 2024-12-12 13:31 UTC by bennettstuart

[Ticket EES-5544](https://dfedigital.atlassian.net/browse/EES-5544)

2025-01-15 18:53 UTC, ntsim requested changes

2025-01-15 18:53 UTC, ntsim commented on src/explore-education-statistics-admin/src/pages/release/data/components/DataFilesTable.tsx
> +const DataFilesTable = ({
Could change to use `export default function`

2025-01-15 18:53 UTC, ntsim commented on src/explore-education-statistics-admin/src/pages/release/data/components/DataFilesTable.tsx
> +            </td>
Currently looks a bit horrible when a data replacement is in progress as we get a horrible big blue box. 

Think we could get rid of the 'Data' part of the replacement label so we don't get wrapping over 3 lines:

![image](https://github.com/user-attachments/assets/86a900b2-75c2-41ee-9326-fb58359d6e80)

2025-01-15 18:53 UTC, ntsim commented on src/explore-education-statistics-admin/src/pages/release/data/components/DataFilesTable.tsx
> +                                <ButtonText>Replace data</ButtonText>
At smaller screens the word 'Replace' breaks across multiple lines and it looks quite weird:

![image](https://github.com/user-attachments/assets/e6b76d05-d83c-4219-9d8b-282976f4ecdd)

2025-01-15 18:53 UTC, ntsim commented on src/explore-education-statistics-admin/src/pages/release/data/components/ReleaseDataUploadsSection.tsx
> +      });
Can rewrite to use awaits

2025-01-15 18:53 UTC, ntsim commented on tests/robot-tests/tests/admin/bau/upload_files.robot
> +    user checks table cell contains    row=1    column=1    expected=Absence in PRUs    parent=testid:Data files table
Why use named parameters? This is pretty inconsistent with how we typically use keywords. Including the parameter names makes the lines much more noisy and hinders readability.

In generally, we use named parameters sparingly throughout the tests e.g. to set optional parameters. We don't usually use them for required parameters like this.

Would revert back to using positional arguments only. Same applies for rest of Robot tests where we've made this change.

2025-01-15 18:53 UTC, ntsim commented on tests/robot-tests/tests/libs/admin-common.robot
> +    ...    wait=%{WAIT_DATA_FILE_IMPORT}
Similar to earlier comment - would switch back to using positional arguments for required parameters.

2025-01-15 18:53 UTC, ntsim commented on tests/robot-tests/tests/libs/tables-common.robot
> +    [Arguments]    ${row}    ${column}    ${expected}    ${parent}=css:table    ${wait}=%{WAIT_SMALL}
Does this need a wait? Typically, we could use some other keyword to check that the table (or something in it) has rendered before checking the table cells.

Most 'check' keywords don't include waits for this reason, so this is fairly inconsistent.

2025-01-15 18:53 UTC, ntsim commented on tests/robot-tests/tests/libs/tables-common.robot
> +    [Arguments]    ${row_cell_text}    ${parent}=css:table    ${wait}=%{WAIT_SMALL}
As above comment - does this need a wait? Similarly, we should be able to use some other keyword to wait for the table (or something in it) before checking table rows.

2025-01-20 13:30 UTC, bennettstuart commented on tests/robot-tests/tests/admin/bau/upload_files.robot
> +    user checks table cell contains    row=1    column=1    expected=Absence in PRUs    parent=testid:Data files table
I feel it makes the test easier to understand, instead of seemingly random strings appended to the end of user created keywords/functions - it's not immediately obvious what the function is doing in my opinion (which is a robot newb's opinion)

I'll remove the names

2025-01-20 13:41 UTC, bennettstuart commented on tests/robot-tests/tests/libs/tables-common.robot
> +    [Arguments]    ${row}    ${column}    ${expected}    ${parent}=css:table    ${wait}=%{WAIT_SMALL}
I suppose I'm exposing the wait param of the underlying `user waits until parent contains element`, am I to rename this to `user waits until table cell contains`?

2025-01-20 15:59 UTC, bennettstuart commented on tests/robot-tests/tests/libs/tables-common.robot
> +    [Arguments]    ${row}    ${column}    ${expected}    ${parent}=css:table    ${wait}=%{WAIT_SMALL}
Was added due to table updating asynchronously to the form submit, but have abstracted the waits into separate keywords

2025-01-22 13:15 UTC, ntsim commented on src/explore-education-statistics-admin/src/pages/release/data/components/DataFilesTable.module.scss
> +      margin-bottom: 1rem;
Seems like the spacing is a bit excessive now:

![image](https://github.com/user-attachments/assets/88e522ee-49b8-47cf-8058-9d66e250caaa)

Additionally, we should be using `govuk-spacing` function for this.

1 spacing unit:

![image](https://github.com/user-attachments/assets/b99d2ce8-34f9-4a6c-9ebd-bc5d2ed081fe)

2 spacing units:

![image](https://github.com/user-attachments/assets/b746a11f-9f89-4a6e-99d9-0a6015c01f75)

Feels like 1 spacing unit might actually be fine

2025-01-22 15:34 UTC, ntsim commented on src/explore-education-statistics-admin/src/pages/release/data/components/DataFilesTable.tsx
> +          <th scope="col">Actions</th>
Seems like we're missing a bunch of columns that appear in the ticket and acceptance criteria? Is this on purpose? If so, the ticket needs to be updated. 

If not, looks like we need to add those in. We'll need to update the tests accordingly as well!

2025-01-22 15:44 UTC, bennettstuart commented on src/explore-education-statistics-admin/src/pages/release/data/components/DataFilesTable.tsx
> +          <th scope="col">Actions</th>
With the addition of the "View details" modal, we've opted to remove some columns to make the rows more concise at first glance wit the added option to see more information. [Cam and I have discussed briefly here](https://dfedigital.atlassian.net/browse/EES-5544?focusedCommentId=100335) in the ticket comments

2025-01-28 16:34 UTC, ntsim commented on src/explore-education-statistics-admin/src/pages/release/data/components/DataFilesTable.tsx
> +          <th scope="col">Actions</th>
The ticket has been updated accordingly now

2025-01-29 16:08 UTC, ntsim approved these changes

2025-01-29 16:19 UTC, merged